### PR TITLE
feat: add PersistQuotaExceededError

### PR DESCRIPTION
**Pull request by daybrush**
#50
스크린샷 2022-01-18 오후 6 44 29

### CODE REVIEW

**Comment by daybrush** [comment]
스크린샷 2022-01-19 오후 7 46 55

**Review by WoodNeck — APPROVED** [review]
LGTM

**Comment by daybrush** [comment]
스크린샷 2022-01-20 오후 4 55 44

**Review by malangfox — APPROVED** [review]
LGTM

**Pull request merged**
